Add pack operator= with scalars (Fix #274)
agenium-scale/boost.simd pull request #275
Opened 2016-09-23 15:36 UTC by ccharly

Hope this won't introduce any sneaky constructions from scalars in the current core implementation. This is definitely a valid use case though. WDYT @jfalcou?

2016-09-23 17:23 UTC, jfalcou commented on include/boost/simd/pack.hpp
> +    template <typename U>
I would maybe prefer having this operator= takes a T by value to prevent hard to cath errors like

   pack<T> x; 
   pack<U> y;

   y = x;

Or keep the const-ref and use SFINAE to check is_convertible<T,U>

2016-09-23 17:24 UTC, jfalcou requested changes

2016-09-23 17:34 UTC, ccharly commented
Indeed, using SFINAE is probably better then. I'll change that on Monday.

Sent from my iPhone

> On 23 Sep 2016, at 19:24, Joel Falcou <notifications@github.com> wrote:
> 
> @jfalcou requested changes on this pull request.
> 
> In include/boost/simd/pack.hpp:
> 
> > @@ -196,6 +196,14 @@ namespace boost { namespace simd
>                        : data_( boost::simd::splat<pack>(value).storage() )
>      {}
>  
> +    /// @brief Scalar assignment operator
> +    template <typename U>
> I would maybe prefer having this operator= takes a T by value to prevent hard to cath errors like
> 
> pack x; 
> pack y;
> 
> y = x;
> 
> Or keep the const-ref and use SFINAE to check is_convertible
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-09-26 16:24 UTC, jfalcou approved these changes

2016-09-26 16:24 UTC, merged