Equal in unit tests
agenium-scale/boost.simd pull request #290
Opened 2016-10-09 20:53 UTC by jtlap

whenever floating are used and result can differ due to IEEE computation  STF_EQUAL(...) is replaced by STF_ULP_EQUAL(...,0.5)

2016-10-10 16:43 UTC, jfalcou requested changes
Discuss the IEEE_EQUAL changes then we'll merge

2016-10-10 16:43 UTC, jfalcou commented on test/function/scalar/abs.cpp
> -  STF_IEEE_EQUAL(bs::std_(abs)(bs::Nan<T>()),  bs::Nan<r_t>());
I'm a bit reluctant to change those. IEEE_EQUAL clearly means what it means when comparing to NaN.

2016-10-11 11:08 UTC, jtlap commented on test/function/scalar/abs.cpp
> -  STF_IEEE_EQUAL(bs::std_(abs)(bs::Nan<T>()),  bs::Nan<r_t>());
It means to redo everything  as the reversal is not so simple. 

All the way the cases where IEEE_EQUAL is full proof have exactly the same outcome than ULP_EQUAL with 0.5. 

Moreover to get back will leave IEEE_EQUAL where it's not sure that a change of proc/archi will not
need the other call.

2016-10-11 17:37 UTC, jfalcou commented on test/function/scalar/abs.cpp
> -  STF_IEEE_EQUAL(bs::std_(abs)(bs::Nan<T>()),  bs::Nan<r_t>());
the arch argument is compelling enough. WIll merge

2016-10-11 17:37 UTC, jfalcou approved these changes

2016-10-11 17:38 UTC, merged