New rec
agenium-scale/boost.simd pull request #333
Opened 2016-11-26 08:34 UTC by jtlap

rec now has only a raw and a regular version.

2016-11-26 11:09 UTC, jfalcou requested changes

2016-11-26 11:09 UTC, jfalcou commented on include/boost/simd/arch/x86/sse1/simd/function/rec.hpp
> +#include <boost/simd/arch/x86/sse1/simd/function/rec_raw.hpp>
if you have nothing else in this file, just put the contents of rec_raw there instead of keeping too much files

2016-11-26 11:09 UTC, jfalcou commented on include/boost/simd/arch/x86/sse1/simd/function/rec.hpp
> +  // No better version of rec than division
if you have nothing else in this file, just put the contents of rec_raw there instead of keeping too much files

2016-11-26 11:09 UTC, jfalcou commented on include/boost/simd/arch/x86/sse2/simd/function/rec.hpp
> +
if you have nothing else in this file, just put the contents of rec_raw there instead of keeping too much files

2016-11-26 11:09 UTC, jfalcou commented on include/boost/simd/arch/common/simd/function/rec_raw.hpp
> +  /// raw_(rec) for floating types: take all version when no speedier exists reverting to rec
this sentence is not english

2016-11-26 11:09 UTC, jfalcou commented on include/boost/simd/arch/ppc/vmx/simd/function/rec.hpp
> +                        , bitwise_and(a0, Mzero<A0>())
isn't it still 0 all the time ??

2016-11-26 11:51 UTC, jtlap commented on include/boost/simd/arch/ppc/vmx/simd/function/rec.hpp
> +                        , bitwise_and(a0, Mzero<A0>())
Mzero or Zero...

2016-11-26 12:08 UTC, jtlap commented on include/boost/simd/arch/x86/sse2/simd/function/rec.hpp
> +
done

2016-11-26 12:08 UTC, jtlap commented on include/boost/simd/arch/common/simd/function/rec_raw.hpp
> +  /// raw_(rec) for floating types: take all version when no speedier exists reverting to rec
ok

2016-11-26 12:08 UTC, jtlap commented on include/boost/simd/arch/x86/sse1/simd/function/rec.hpp
> +#include <boost/simd/arch/x86/sse1/simd/function/rec_raw.hpp>
done

2016-11-26 15:11 UTC, jfalcou commented on bench/function/simd/rec.raw.hpp
> +// -------------------------------------------------------------------------------------------------
this need to be a .cpp

2016-11-26 16:36 UTC, jtlap commented on bench/function/simd/rec.raw.hpp
> +// -------------------------------------------------------------------------------------------------
file suppressed the cpp already existed

2016-11-28 10:53 UTC, jfalcou approved these changes

2016-11-29 17:50 UTC, merged