Trunc for double
agenium-scale/boost.simd pull request #340
Opened 2016-12-10 13:33 UTC by jtlap

2016-12-10 18:05 UTC, jfalcou requested changes
the PR tlaks abotu trunc but no trunc files are touched ???

2016-12-10 18:05 UTC, jfalcou commented on include/boost/simd/arch/common/simd/function/toint.hpp
> +                          , bd::cpu_
this miss a is_native<X> check

2016-12-10 18:05 UTC, jfalcou commented on test/function/simd/toint.saturated.cpp
> +//     STF_EQUAL(bs::saturated_(bs::toint)(v), r_t(iv));
spurriosu comments & I/O

2016-12-10 18:56 UTC, jtlap commented on test/function/simd/toint.saturated.cpp
> +//     STF_EQUAL(bs::saturated_(bs::toint)(v), r_t(iv));
suppressed

2016-12-10 18:56 UTC, jtlap commented on include/boost/simd/arch/common/simd/function/toint.hpp
> +                          , bd::cpu_
done

2016-12-11 18:02 UTC, jtlap commented
in fact it is toint saturated, the change of which implies modification of trunc behaviour.

2016-12-13 09:37 UTC, jfalcou approved these changes

2016-12-13 09:38 UTC, merged