Doc func def
agenium-scale/boost.simd pull request #453
Opened 2017-02-13 01:56 UTC by gquintin

- Cleanup all public function declaration (primary and only objective at the beginning)
- Fix all mistakes I could see (indentation, spelling, missing docs)
- Fix all doxygen warnings except the "Compound [...] is not documented."'s

2017-02-13 13:14 UTC, jfalcou commented on include/boost/simd/function/exponent.hpp
> +  as_integer_t<Value> exponent(exValue const& x);
Why changing this ?

2017-02-13 13:16 UTC, jfalcou commented on include/boost/simd/function/genmask.hpp
> +    This function object returns a mask of bits: full of ones if the
sentence is broken

2017-02-13 13:17 UTC, jfalcou commented on include/boost/simd/function/genmaskc.hpp
> +    This function object returns a mask of bits: full of ones if the
you just wrote somethign else in genmask

2017-02-13 13:17 UTC, jfalcou commented on include/boost/simd/function/frac.hpp
> +    This function object returns the fractional part of the input i.e. `x-trunc(x)`.
why the change ?

2017-02-13 13:18 UTC, jfalcou commented on include/boost/simd/function/cosd.hpp
> +     See @ref cos for further details
this is useless as the first ref linsk already

2017-02-13 13:19 UTC, jfalcou commented on include/boost/simd/function/cospi.hpp
> +  Value cospi(Value const& x);
Are you sure ?

2017-02-14 08:53 UTC, jfalcou requested changes

2017-02-14 08:53 UTC, jfalcou commented on include/boost/simd/function/interleave_even.hpp
> +    This function object cComputes a vector from a combination of the two inputs.
"computes"

2017-02-14 08:53 UTC, jfalcou commented on include/boost/simd/function/inrad.hpp
> +    This function object converts degree to radian.
"converts its argument in degree to radian"

2017-02-14 08:53 UTC, jfalcou commented on include/boost/simd/function/interleave_first.hpp
> +    This function object cComputes a vector from a combination of the two inputs.
"computes"

2017-02-14 08:53 UTC, jfalcou commented on include/boost/simd/function/interleave_odd.hpp
> +    This function object cComputes a vector from a combination of the two inputs.
"computes"

2017-02-14 08:53 UTC, jfalcou commented on include/boost/simd/function/interleave_second.hpp
> +    This function object cComputes a vector from a combination of the two inputs.
"computes"

2017-02-14 09:40 UTC, jtlap commented on include/boost/simd/function/exponent.hpp
> +  as_integer_t<Value> exponent(exValue const& x);
ex is a typo, but exponent admits integral enties

2017-02-14 09:40 UTC, jtlap commented on include/boost/simd/function/genmask.hpp
> +    This function object returns a mask of bits: full of ones if the
corrected

2017-02-14 09:41 UTC, jtlap commented on include/boost/simd/function/genmaskc.hpp
> +    This function object returns a mask of bits: full of ones if the
corrected

2017-02-14 09:43 UTC, jtlap commented on include/boost/simd/function/interleave_first.hpp
> +    This function object cComputes a vector from a combination of the two inputs.
done

2017-02-14 09:43 UTC, jtlap commented on include/boost/simd/function/interleave_odd.hpp
> +    This function object cComputes a vector from a combination of the two inputs.
done

2017-02-14 09:43 UTC, jtlap commented on include/boost/simd/function/interleave_second.hpp
> +    This function object cComputes a vector from a combination of the two inputs.
done

2017-02-14 17:15 UTC, jfalcou commented on include/boost/simd/function/unary_minus.hpp
> +    - `saturated_` ensurs that `saturated_(unary_minus)(Valmin<T>())` is `Valmin<T>()`
"ensures"

2017-02-15 06:46 UTC, jfalcou approved these changes

2017-02-15 13:42 UTC, merged