pack aware algorithms
agenium-scale/boost.simd pull request #480
Opened 2017-03-09 14:48 UTC by jtlap

2017-03-09 16:55 UTC, jfalcou commented
looks like the list of test is incorrect

2017-03-10 07:19 UTC, jtlap commented
travis time out

2017-03-10 18:20 UTC, jfalcou requested changes
- Apply the "Vectorizable" doc trick everywhere. 
- Could we have a bunch of benchamrks with those ?

2017-03-10 18:20 UTC, jfalcou commented on include/boost/simd/algorithm/all_of.hpp
> +    return all_of(first, last, detail::identity());
is it identity or should it be is_nez ?

2017-03-10 18:20 UTC, jfalcou commented on include/boost/simd/algorithm/any_of.hpp
> +      - @c first and @c last must be pointers to a type which can be used within
We now have documentation for this. YOu shoudl say " must be pointers to Vectorizable type" to link to the proper cocnept doc

2017-03-10 18:20 UTC, jfalcou commented on include/boost/simd/algorithm/any_of.hpp
> +    return any_of(first, last, detail::identity());
same comment, is_nez ?

2017-03-10 18:20 UTC, jfalcou commented on include/boost/simd/algorithm/fill.hpp
> +    pack<T> v(value);
this can be created as a temporary in the std::fill call

2017-03-10 18:20 UTC, jfalcou commented on include/boost/simd/algorithm/iota.hpp
> +  /* overload */
/* overload */ doesnt do what you think it does in Doxygen
Then why isn't this one calling the other one ?

2017-03-10 18:20 UTC, jfalcou commented on include/boost/simd/algorithm/lexicographical_compare.hpp
> +//    auto last2b = shorter ? last2 : first2+d1;
if it's useless, remove it

2017-03-10 18:20 UTC, jfalcou commented on include/boost/simd/algorithm/max_element.hpp
> +
Not sure this one is a win in term of performances as we scoop over the data twice.

2017-03-10 18:20 UTC, jfalcou commented on include/boost/simd/algorithm/replace.hpp
> +//  When c++14
I think you cna locally use one of the Boost.Config macro to check for Polymorphic lambda support and have this already

2017-03-10 18:20 UTC, jfalcou commented on include/boost/simd/detail/identity.hpp
> +      template < typename U>
isn't it what unary_plus should be ?

2017-03-10 19:06 UTC, jtlap commented on include/boost/simd/algorithm/all_of.hpp
> +    return all_of(first, last, detail::identity());
all(x) is the same that all(is_nez(x)) which will be done internally only if necessary...

2017-03-10 19:06 UTC, jtlap commented on include/boost/simd/algorithm/any_of.hpp
> +    return any_of(first, last, detail::identity());
same reply

2017-03-10 19:09 UTC, jtlap commented on include/boost/simd/algorithm/fill.hpp
> +    pack<T> v(value);
ok

2017-03-10 19:11 UTC, jtlap commented on include/boost/simd/algorithm/iota.hpp
> +  /* overload */
minor optimization if step is 1

2017-03-10 19:12 UTC, jtlap commented on include/boost/simd/algorithm/lexicographical_compare.hpp
> +//    auto last2b = shorter ? last2 : first2+d1;
done

2017-03-10 19:13 UTC, jtlap commented on include/boost/simd/algorithm/max_element.hpp
> +
until bad bench or better solution, let us keep it.

2017-03-10 19:15 UTC, jtlap commented on include/boost/simd/algorithm/replace.hpp
> +//  When c++14
In that the existing version is slightly better as old_val and newval are splat only once.
I suppress the comment.

2017-03-10 19:16 UTC, jtlap commented on include/boost/simd/detail/identity.hpp
> +      template < typename U>
problem of scalar promotion for unary_plus

2017-03-10 19:39 UTC, jtlap commented
I have rebased too

2017-03-10 19:53 UTC, jfalcou commented on include/boost/simd/detail/identity.hpp
> +      template < typename U>
OK

2017-03-10 19:53 UTC, jfalcou commented on include/boost/simd/algorithm/replace.hpp
> +//  When c++14
OK

2017-03-10 19:53 UTC, jfalcou commented on include/boost/simd/algorithm/max_element.hpp
> +
OK

2017-03-10 19:53 UTC, jfalcou commented on include/boost/simd/algorithm/iota.hpp
> +  /* overload */
OK

2017-03-10 19:53 UTC, jfalcou commented on include/boost/simd/algorithm/all_of.hpp
> +    return all_of(first, last, detail::identity());
OK

2017-03-10 19:54 UTC, jfalcou approved these changes

2017-03-11 07:29 UTC, jtlap commented
a bad find/replace I will correct that

2017-03-11 13:05 UTC, jtlap commented
travis time out again

2017-03-13 08:05 UTC, merged